### ISSUE TITLE
NAN when training with transformer-preprocess: n on 2080ti, works fine on 1080ti

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-dev#699]
### Bug description
I have been training marian models on data from Mueller et. al (2019): Domain robustness in neural machine translation.
I'm using the following config:

```
devices:
 - 0
 - 1
 - 2
 - 3

workspace: 7000
log: /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_medical_all/train.log
model: /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_medical_all/model.npz

train-sets:
  - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/medical/train.bpe.all.de
  - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/medical/train.bpe.all.en
seed: 1111
vocabs:
  - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_medical_all/vocab.deen.yml
  - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_medical_all/vocab.deen.yml
task: transformer-base
dim-vocabs:
  - 32000
  - 32000
shuffle-in-ram: true
# Validation set options
valid-sets:
  - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/medical/dev.bpe.all.de
  - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/medical/dev.bpe.all.en
valid-freq: 2000
valid-metrics:
  - ce-mean-words
  - perplexity
  - bleu
label-smoothing: 0.1
#mini-batch-fit: false
#mini-batch: 64
#mini-batch-words: 4096
transformer-dropout-attention: 0.1
transformer-dropout-ffn: 0.1
#@TODO next thing to try the postprocess/preprocess normalise
transformer-postprocess: da
transformer-preprocess: n
early-stopping: 10
beam-size: 6
normalize: 0.6
max-length-factor: 3
word-penalty: 0
allow-unk: false
n-best: false
valid-mini-batch: 8
valid-max-length: 500
valid-translation-output: /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_medical_all/valid.bpe.en.output
keep-best: true
valid-log: /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_medical_all/valid.log
```
And this trains a good model when trained on 4x1080ti GPU. On  2x2080ti however with almost the same config (using 2 GPUs instead of 4), training loss becomes NaN on the 4th update. If i use `--optimizer-delay: 2`  to compensate for using only 2 GPUs, I get the NaN on the 38th update instead.

I also tried going back to a 2x1080ti and training with exactly the same settings. I got to 500 updates with no issues and I stopped the training.

### How to reproduce
I was unable to test with the exact same config file as I didn't have 4x2080ti. Instead i used 2GPUs with and without `optimizer-delay: 2`. Both settings work with 1080ti (tested up to 500 updates) and fail with 2080ti.

The preprocessed dataset may be located here: https://www.nbogoychev.com/files/medical.tar.gz

### Context
* Marian version: `v1.9.33; 8413c77 2020-08-18 23:55:53 +0100`
* CUDA version: 10.2
* CMake command: `cmake .. -DCOMPILE_CPU=OFF`
```
s1031254@vor:~/marian-dev/build_new$ ./marian --build-info all
AVX2_FOUND=true
AVX512_FOUND=true
AVX_FOUND=true
BUILD_ARCH=native
CMAKE_AR=/usr/bin/ar
CMAKE_BUILD_TYPE=Release
CMAKE_COLOR_MAKEFILE=ON
CMAKE_CXX_COMPILER=/usr/bin/c++
CMAKE_CXX_FLAGS=-std=c++11 -pthread -Wl,--no-as-needed -fPIC -Wno-unused-result -Wno-unknown-warning-option  -march=native  -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mavx512f -DCUDA_FOUND -DUSE_NCCL
CMAKE_CXX_FLAGS_DEBUG=-O0 -g -rdynamic
CMAKE_CXX_FLAGS_MINSIZEREL=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE=-O3 -m64 -funroll-loops -g -rdynamic
CMAKE_CXX_FLAGS_RELWITHDEBINFO=-O3 -m64 -funroll-loops -g -rdynamic
CMAKE_C_COMPILER=/usr/bin/cc
CMAKE_C_FLAGS=-pthread -Wl,--no-as-needed -fPIC -Wno-unused-result -Wno-unknown-warning-option  -march=native  -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mavx512f
CMAKE_C_FLAGS_DEBUG=-O0 -g -rdynamic
CMAKE_C_FLAGS_MINSIZEREL=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE=-O3 -m64 -funroll-loops -g -rdynamic
CMAKE_C_FLAGS_RELWITHDEBINFO=-O3 -m64 -funroll-loops -g -rdynamic
CMAKE_EXPORT_COMPILE_COMMANDS=OFF
CMAKE_INSTALL_PREFIX=/usr/local
CMAKE_LINKER=/usr/bin/ld
CMAKE_MAKE_PROGRAM=/usr/bin/make
CMAKE_NM=/usr/bin/nm
CMAKE_OBJCOPY=/usr/bin/objcopy
CMAKE_OBJDUMP=/usr/bin/objdump
CMAKE_RANLIB=/usr/bin/ranlib
CMAKE_SKIP_INSTALL_RPATH=NO
CMAKE_SKIP_RPATH=NO
CMAKE_STRIP=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE=FALSE
COMPILE_CPU=OFF
COMPILE_CUDA=ON
COMPILE_CUDA_SM35=ON
COMPILE_CUDA_SM50=ON
COMPILE_CUDA_SM60=ON
COMPILE_CUDA_SM70=ON
COMPILE_CUDA_SM75=ON
COMPILE_EXAMPLES=OFF
COMPILE_SERVER=OFF
COMPILE_TESTS=OFF
CUDA_64_BIT_DEVICE_CODE=ON
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE=ON
CUDA_BUILD_CUBIN=OFF
CUDA_BUILD_EMULATION=OFF
CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so
CUDA_CUDA_LIBRARY=/usr/lib/x86_64-linux-gnu/libcuda.so
CUDA_HOST_COMPILATION_CPP=ON
CUDA_HOST_COMPILER=/usr/bin/cc
CUDA_NVCC_EXECUTABLE=/usr/local/cuda/bin/nvcc
CUDA_NVCC_FLAGS=-DCUDA_FOUND-DUSE_NCCL--default-streamper-thread-O3-g--use_fast_math-arch=sm_35-gencode=arch=compute_35,code=sm_35-gencode=arch=compute_50,code=sm_50-gencode=arch=compute_52,code=sm_52-gencode=arch=compute_60,code=sm_60-gencode=arch=compute_61,code=sm_61-gencode=arch=compute_70,code=sm_70-gencode=arch=compute_70,code=compute_70-gencode=arch=compute_75,code=sm_75-gencode=arch=compute_75,code=compute_75-ccbin/usr/bin/cc-std=c++11-Xcompiler -fPIC-Xcompiler -Wno-unused-result-Xcompiler -Wno-deprecated-Xcompiler -Wno-pragmas-Xcompiler -Wno-unused-value-Xcompiler -Werror-Xcompiler -msse2-Xcompiler -msse3-Xcompiler -msse4.1-Xcompiler -msse4.2-Xcompiler -mavx-Xcompiler -mavx2-Xcompiler -mavx512f
CUDA_PROPAGATE_HOST_FLAGS=OFF
CUDA_SDK_ROOT_DIR=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION=OFF
CUDA_TOOLKIT_INCLUDE=/usr/local/cuda/include
CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
CUDA_TOOLKIT_TARGET_DIR=/usr/local/cuda
CUDA_USE_STATIC_CUDA_RUNTIME=ON
CUDA_VERBOSE_BUILD=OFF
CUDA_VERSION=10.2
CUDA_cublas_LIBRARY=/usr/lib/x86_64-linux-gnu/libcublas.so
CUDA_cudart_static_LIBRARY=/usr/local/cuda/lib64/libcudart_static.a
CUDA_cufft_LIBRARY=/usr/local/cuda/lib64/libcufft.so
CUDA_cupti_LIBRARY=CUDA_cupti_LIBRARY-NOTFOUND
CUDA_curand_LIBRARY=/usr/local/cuda/lib64/libcurand.so
CUDA_cusolver_LIBRARY=/usr/local/cuda/lib64/libcusolver.so
CUDA_cusparse_LIBRARY=/usr/local/cuda/lib64/libcusparse.so
CUDA_nppc_LIBRARY=/usr/local/cuda/lib64/libnppc.so
CUDA_nppi_LIBRARY=CUDA_nppi_LIBRARY-NOTFOUND
CUDA_npps_LIBRARY=/usr/local/cuda/lib64/libnpps.so
CUDA_rt_LIBRARY=/usr/lib/x86_64-linux-gnu/librt.so
GIT_EXECUTABLE=/usr/bin/git
SSE2_FOUND=true
SSE3_FOUND=true
SSE4_1_FOUND=true
SSE4_2_FOUND=true
SSSE3_FOUND=true
Tcmalloc_INCLUDE_DIR=/usr/include
Tcmalloc_LIBRARY=/usr/lib/libtcmalloc_minimal.so
USE_CCACHE=OFF
USE_CUDNN=OFF
USE_DOXYGEN=ON
USE_FBGEMM=OFF
USE_MKL=ON
USE_MPI=OFF
USE_NCCL=ON
USE_SENTENCEPIECE=OFF
USE_STATIC_LIBS=OFF
```
*  Train log:
```
~/marian-dev/build_new/marian -c config.all.tstspeed.yml
[2020-08-18 23:58:09] [marian] Marian v1.9.33; 8413c77 2020-08-18 23:55:53 +0100
[2020-08-18 23:58:09] [marian] Running on vor as process 412538 with command line:
[2020-08-18 23:58:09] [marian] /home/s1031254/marian-dev/build_new/marian -c config.all.tstspeed.yml
[2020-08-18 23:58:09] [config] after-batches: 0
[2020-08-18 23:58:09] [config] after-epochs: 0
[2020-08-18 23:58:09] [config] all-caps-every: 0
[2020-08-18 23:58:09] [config] allow-unk: false
[2020-08-18 23:58:09] [config] authors: false
[2020-08-18 23:58:09] [config] beam-size: 6
[2020-08-18 23:58:09] [config] bert-class-symbol: "[CLS]"
[2020-08-18 23:58:09] [config] bert-mask-symbol: "[MASK]"
[2020-08-18 23:58:09] [config] bert-masking-fraction: 0.15
[2020-08-18 23:58:09] [config] bert-sep-symbol: "[SEP]"
[2020-08-18 23:58:09] [config] bert-train-type-embeddings: true
[2020-08-18 23:58:09] [config] bert-type-vocab-size: 2
[2020-08-18 23:58:09] [config] build-info: ""
[2020-08-18 23:58:09] [config] cite: false
[2020-08-18 23:58:09] [config] clip-gemm: 0
[2020-08-18 23:58:09] [config] clip-norm: 0
[2020-08-18 23:58:09] [config] cost-scaling:
[2020-08-18 23:58:09] [config]   []
[2020-08-18 23:58:09] [config] cost-type: ce-mean-words
[2020-08-18 23:58:09] [config] cpu-threads: 0
[2020-08-18 23:58:09] [config] data-weighting: ""
[2020-08-18 23:58:09] [config] data-weighting-type: sentence
[2020-08-18 23:58:09] [config] dec-cell: gru
[2020-08-18 23:58:09] [config] dec-cell-base-depth: 2
[2020-08-18 23:58:09] [config] dec-cell-high-depth: 1
[2020-08-18 23:58:09] [config] dec-depth: 6
[2020-08-18 23:58:09] [config] devices:
[2020-08-18 23:58:09] [config]   - 4
[2020-08-18 23:58:09] [config]   - 5
[2020-08-18 23:58:09] [config] dim-emb: 512
[2020-08-18 23:58:09] [config] dim-rnn: 1024
[2020-08-18 23:58:09] [config] dim-vocabs:
[2020-08-18 23:58:09] [config]   - 32000
[2020-08-18 23:58:09] [config]   - 32000
[2020-08-18 23:58:09] [config] disp-first: 0
[2020-08-18 23:58:09] [config] disp-freq: 100
[2020-08-18 23:58:09] [config] disp-label-counts: false
[2020-08-18 23:58:09] [config] dropout-rnn: 0
[2020-08-18 23:58:09] [config] dropout-src: 0
[2020-08-18 23:58:09] [config] dropout-trg: 0
[2020-08-18 23:58:09] [config] dump-config: ""
[2020-08-18 23:58:09] [config] early-stopping: 10
[2020-08-18 23:58:09] [config] embedding-fix-src: false
[2020-08-18 23:58:09] [config] embedding-fix-trg: false
[2020-08-18 23:58:09] [config] embedding-normalization: false
[2020-08-18 23:58:09] [config] embedding-vectors:
[2020-08-18 23:58:09] [config]   []
[2020-08-18 23:58:09] [config] enc-cell: gru
[2020-08-18 23:58:09] [config] enc-cell-depth: 1
[2020-08-18 23:58:09] [config] enc-depth: 6
[2020-08-18 23:58:09] [config] enc-type: bidirectional
[2020-08-18 23:58:09] [config] english-title-case-every: 0
[2020-08-18 23:58:09] [config] exponential-smoothing: 0.0001
[2020-08-18 23:58:09] [config] factor-weight: 1
[2020-08-18 23:58:09] [config] grad-dropping-momentum: 0
[2020-08-18 23:58:09] [config] grad-dropping-rate: 0
[2020-08-18 23:58:09] [config] grad-dropping-warmup: 100
[2020-08-18 23:58:09] [config] gradient-checkpointing: false
[2020-08-18 23:58:09] [config] guided-alignment: none
[2020-08-18 23:58:09] [config] guided-alignment-cost: mse
[2020-08-18 23:58:09] [config] guided-alignment-weight: 0.1
[2020-08-18 23:58:09] [config] ignore-model-config: false
[2020-08-18 23:58:09] [config] input-types:
[2020-08-18 23:58:09] [config]   []
[2020-08-18 23:58:09] [config] interpolate-env-vars: false
[2020-08-18 23:58:09] [config] keep-best: true
[2020-08-18 23:58:09] [config] label-smoothing: 0.1
[2020-08-18 23:58:09] [config] layer-normalization: false
[2020-08-18 23:58:09] [config] learn-rate: 0.0003
[2020-08-18 23:58:09] [config] lemma-dim-emb: 0
[2020-08-18 23:58:09] [config] log: /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_speed/train.log
[2020-08-18 23:58:09] [config] log-level: info
[2020-08-18 23:58:09] [config] log-time-zone: ""
[2020-08-18 23:58:09] [config] lr-decay: 0
[2020-08-18 23:58:09] [config] lr-decay-freq: 50000
[2020-08-18 23:58:09] [config] lr-decay-inv-sqrt:
[2020-08-18 23:58:09] [config]   - 16000
[2020-08-18 23:58:09] [config] lr-decay-repeat-warmup: false
[2020-08-18 23:58:09] [config] lr-decay-reset-optimizer: false
[2020-08-18 23:58:09] [config] lr-decay-start:
[2020-08-18 23:58:09] [config]   - 10
[2020-08-18 23:58:09] [config]   - 1
[2020-08-18 23:58:09] [config] lr-decay-strategy: epoch+stalled
[2020-08-18 23:58:09] [config] lr-report: false
[2020-08-18 23:58:09] [config] lr-warmup: 16000
[2020-08-18 23:58:09] [config] lr-warmup-at-reload: false
[2020-08-18 23:58:09] [config] lr-warmup-cycle: false
[2020-08-18 23:58:09] [config] lr-warmup-start-rate: 0
[2020-08-18 23:58:09] [config] max-length: 100
[2020-08-18 23:58:09] [config] max-length-crop: false
[2020-08-18 23:58:09] [config] max-length-factor: 3
[2020-08-18 23:58:09] [config] maxi-batch: 1000
[2020-08-18 23:58:09] [config] maxi-batch-sort: trg
[2020-08-18 23:58:09] [config] mini-batch: 1000
[2020-08-18 23:58:09] [config] mini-batch-fit: true
[2020-08-18 23:58:09] [config] mini-batch-fit-step: 10
[2020-08-18 23:58:09] [config] mini-batch-track-lr: false
[2020-08-18 23:58:09] [config] mini-batch-warmup: 0
[2020-08-18 23:58:09] [config] mini-batch-words: 0
[2020-08-18 23:58:09] [config] mini-batch-words-ref: 0
[2020-08-18 23:58:09] [config] model: /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_medical_all/model.npz
[2020-08-18 23:58:09] [config] multi-loss-type: sum
[2020-08-18 23:58:09] [config] multi-node: false
[2020-08-18 23:58:09] [config] multi-node-overlap: true
[2020-08-18 23:58:09] [config] n-best: false
[2020-08-18 23:58:09] [config] no-nccl: false
[2020-08-18 23:58:09] [config] no-reload: false
[2020-08-18 23:58:09] [config] no-restore-corpus: false
[2020-08-18 23:58:09] [config] normalize: 0.6
[2020-08-18 23:58:09] [config] normalize-gradient: false
[2020-08-18 23:58:09] [config] num-devices: 0
[2020-08-18 23:58:09] [config] optimizer: adam
[2020-08-18 23:58:09] [config] optimizer-delay: 1
[2020-08-18 23:58:09] [config] optimizer-params:
[2020-08-18 23:58:09] [config]   - 0.9
[2020-08-18 23:58:09] [config]   - 0.98
[2020-08-18 23:58:09] [config]   - 1e-09
[2020-08-18 23:58:09] [config] overwrite: false
[2020-08-18 23:58:09] [config] precision:
[2020-08-18 23:58:09] [config]   - float32
[2020-08-18 23:58:09] [config]   - float32
[2020-08-18 23:58:09] [config]   - float32
[2020-08-18 23:58:09] [config] pretrained-model: ""
[2020-08-18 23:58:09] [config] quiet: false
[2020-08-18 23:58:09] [config] quiet-translation: false
[2020-08-18 23:58:09] [config] relative-paths: false
[2020-08-18 23:58:09] [config] right-left: false
[2020-08-18 23:58:09] [config] save-freq: 10000u
[2020-08-18 23:58:09] [config] seed: 1111
[2020-08-18 23:58:09] [config] shuffle: data
[2020-08-18 23:58:09] [config] shuffle-in-ram: true
[2020-08-18 23:58:09] [config] skip: false
[2020-08-18 23:58:09] [config] sqlite: ""
[2020-08-18 23:58:09] [config] sqlite-drop: false
[2020-08-18 23:58:09] [config] sync-sgd: true
[2020-08-18 23:58:09] [config] tempdir: /tmp
[2020-08-18 23:58:09] [config] tied-embeddings: false
[2020-08-18 23:58:09] [config] tied-embeddings-all: true
[2020-08-18 23:58:09] [config] tied-embeddings-src: false
[2020-08-18 23:58:09] [config] train-sets:
[2020-08-18 23:58:09] [config]   - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/medical/train.bpe.all.de
[2020-08-18 23:58:09] [config]   - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/medical/train.bpe.all.en
[2020-08-18 23:58:09] [config] transformer-aan-activation: swish
[2020-08-18 23:58:09] [config] transformer-aan-depth: 2
[2020-08-18 23:58:09] [config] transformer-aan-nogate: false
[2020-08-18 23:58:09] [config] transformer-decoder-autoreg: self-attention
[2020-08-18 23:58:09] [config] transformer-depth-scaling: false
[2020-08-18 23:58:09] [config] transformer-dim-aan: 2048
[2020-08-18 23:58:09] [config] transformer-dim-ffn: 2048
[2020-08-18 23:58:09] [config] transformer-dropout: 0.1
[2020-08-18 23:58:09] [config] transformer-dropout-attention: 0.1
[2020-08-18 23:58:09] [config] transformer-dropout-ffn: 0.1
[2020-08-18 23:58:09] [config] transformer-ffn-activation: relu
[2020-08-18 23:58:09] [config] transformer-ffn-depth: 2
[2020-08-18 23:58:09] [config] transformer-guided-alignment-layer: last
[2020-08-18 23:58:09] [config] transformer-heads: 8
[2020-08-18 23:58:09] [config] transformer-no-projection: false
[2020-08-18 23:58:09] [config] transformer-postprocess: da
[2020-08-18 23:58:09] [config] transformer-postprocess-emb: d
[2020-08-18 23:58:09] [config] transformer-preprocess: n
[2020-08-18 23:58:09] [config] transformer-tied-layers:
[2020-08-18 23:58:09] [config]   []
[2020-08-18 23:58:09] [config] transformer-train-position-embeddings: false
[2020-08-18 23:58:09] [config] tsv: false
[2020-08-18 23:58:09] [config] tsv-fields: 0
[2020-08-18 23:58:09] [config] type: transformer
[2020-08-18 23:58:09] [config] ulr: false
[2020-08-18 23:58:09] [config] ulr-dim-emb: 0
[2020-08-18 23:58:09] [config] ulr-dropout: 0
[2020-08-18 23:58:09] [config] ulr-keys-vectors: ""
[2020-08-18 23:58:09] [config] ulr-query-vectors: ""
[2020-08-18 23:58:09] [config] ulr-softmax-temperature: 1
[2020-08-18 23:58:09] [config] ulr-trainable-transformation: false
[2020-08-18 23:58:09] [config] unlikelihood-loss: false
[2020-08-18 23:58:09] [config] valid-freq: 2000
[2020-08-18 23:58:09] [config] valid-log: /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_speed/valid.log
[2020-08-18 23:58:09] [config] valid-max-length: 500
[2020-08-18 23:58:09] [config] valid-metrics:
[2020-08-18 23:58:09] [config]   - ce-mean-words
[2020-08-18 23:58:09] [config]   - perplexity
[2020-08-18 23:58:09] [config]   - bleu
[2020-08-18 23:58:09] [config] valid-mini-batch: 8
[2020-08-18 23:58:09] [config] valid-reset-stalled: false
[2020-08-18 23:58:09] [config] valid-script-args:
[2020-08-18 23:58:09] [config]   []
[2020-08-18 23:58:09] [config] valid-script-path: ""
[2020-08-18 23:58:09] [config] valid-sets:
[2020-08-18 23:58:09] [config]   - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/medical/dev.bpe.all.de
[2020-08-18 23:58:09] [config]   - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/medical/dev.bpe.all.en
[2020-08-18 23:58:09] [config] valid-translation-output: /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_medical_speed/valid.bpe.en.output
[2020-08-18 23:58:09] [config] vocabs:
[2020-08-18 23:58:09] [config]   - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_speed/vocab.deen.yml
[2020-08-18 23:58:09] [config]   - /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_speed/vocab.deen.yml
[2020-08-18 23:58:09] [config] word-penalty: 0
[2020-08-18 23:58:09] [config] word-scores: false
[2020-08-18 23:58:09] [config] workspace: 7000
[2020-08-18 23:58:09] [config] Model is being created with Marian v1.9.33; 8413c77 2020-08-18 23:55:53 +0100
[2020-08-18 23:58:09] Using synchronous SGD
[2020-08-18 23:58:09] [data] Loading vocabulary from JSON/Yaml file /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_speed/vocab.deen.yml
[2020-08-18 23:58:09] [data] Setting vocabulary size for input 0 to 32,000
[2020-08-18 23:58:09] [data] Loading vocabulary from JSON/Yaml file /mnt/gna0/nbogoych/hallucinations/domain-robustness-nospm/data/de-en/model_speed/vocab.deen.yml
[2020-08-18 23:58:09] [data] Setting vocabulary size for input 1 to 32,000
[2020-08-18 23:58:09] [comm] Compiled without MPI support. Running as a single process on vor
[2020-08-18 23:58:09] [batching] Collecting statistics for batch fitting with step size 10
[2020-08-18 23:58:10] [memory] Extending reserved space to 7040 MB (device gpu4)
[2020-08-18 23:58:10] [memory] Extending reserved space to 7040 MB (device gpu5)
[2020-08-18 23:58:10] [comm] Using NCCL 2.3.7 for GPU communication
[2020-08-18 23:58:10] [comm] NCCLCommunicator constructed successfully
[2020-08-18 23:58:10] [training] Using 2 GPUs
[2020-08-18 23:58:10] [logits] Applying loss function for 1 factor(s)
[2020-08-18 23:58:10] [memory] Reserving 230 MB, device gpu4
[2020-08-18 23:58:11] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2020-08-18 23:58:11] [memory] Reserving 230 MB, device gpu4
[2020-08-18 23:58:17] [batching] Done. Typical MB size is 9,850 target words
[2020-08-18 23:58:17] [memory] Extending reserved space to 7040 MB (device gpu4)
[2020-08-18 23:58:18] [memory] Extending reserved space to 7040 MB (device gpu5)
[2020-08-18 23:58:18] [comm] Using NCCL 2.3.7 for GPU communication
[2020-08-18 23:58:18] [comm] NCCLCommunicator constructed successfully
[2020-08-18 23:58:18] [training] Using 2 GPUs
[2020-08-18 23:58:18] Training started
[2020-08-18 23:58:18] [data] Shuffling data
[2020-08-18 23:58:18] [data] Done reading 1,091,872 sentences
[2020-08-18 23:58:18] [data] Done shuffling 1,091,872 sentences (cached in RAM)
[2020-08-18 23:58:34] [training] Batches are processed as 1 process(es) x 2 devices/process
[2020-08-18 23:58:34] [memory] Reserving 230 MB, device gpu5
[2020-08-18 23:58:34] [memory] Reserving 230 MB, device gpu4
[2020-08-18 23:58:34] [memory] Reserving 230 MB, device gpu4
[2020-08-18 23:58:34] [memory] Reserving 230 MB, device gpu5
[2020-08-18 23:58:34] [memory] Reserving 115 MB, device gpu4
[2020-08-18 23:58:34] [memory] Reserving 115 MB, device gpu5
[2020-08-18 23:58:35] [memory] Reserving 230 MB, device gpu4
[2020-08-18 23:58:35] [memory] Reserving 230 MB, device gpu5
[2020-08-18 23:58:35] [training] skipping 4-th update due to loss being nan
[2020-08-18 23:58:36] [training] skipping 5-th update due to loss being nan
[2020-08-18 23:58:36] [training] skipping 6-th update due to loss being nan
[2020-08-18 23:58:36] [training] skipping 7-th update due to loss being nan
[2020-08-18 23:58:36] Error: CUDA error 700 'an illegal memory access was encountered' - /home/s1031254/marian-dev/src/tensors/gpu/cuda_helpers.h:67: cudaMemcpy(dest, start, (end - start) * sizeof(T), cudaMemcpyDefault)
[2020-08-18 23:58:36] Error: Aborted from void CudaCopy(const T*, const T*, T*) [with T = float] in /home/s1031254/marian-dev/src/tensors/gpu/cuda_helpers.h:67

[CALL STACK]
[0xe05ab3]          void  CudaCopy  <float>(float const*,  float const*,  float*) + 0x2f3
[0xe1b4fe]          void marian::gpu::  copy  <float>(std::shared_ptr<marian::Backend>,  float const*,  float const*,  float*) + 0x43e
[0x999496]          void marian::TensorBase::  set  <float>(float const*,  float const*) + 0x7b6
[0x99a532]          std::_Function_handler<void (IntrusivePtr<marian::TensorBase>),std::shared_ptr<marian::inits::NodeInitializer> marian::inits::fromVector<float>(std::vector<float,std::allocator<float>>&&)::{lambda(IntrusivePtr<marian::TensorBase>)#1}>::  _M_invoke  (std::_Any_data const&,  IntrusivePtr<marian::TensorBase>&&) + 0x22
[0x996e01]          marian::inits::LambdaInitConvert::  apply  (IntrusivePtr<marian::TensorBase>) + 0x861
[0x989438]          marian::ConstantNode::  init  ()                   + 0x48
[0x8b2af5]          marian::ExpressionGraph::  forward  (std::__cxx11::list<IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>,std::allocator<IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>>>&,  bool) + 0x95
[0x8b47f4]          marian::ExpressionGraph::  forwardNext  ()         + 0x184
[0xaf77b2]                                                            
[0xb58f36]          std::future<std::result_of<std::function<void (unsigned long,unsigned long,unsigned long)> const& (unsigned long&,unsigned long&,unsigned long&)>::type> marian::ThreadPool::enqueue<std::function<void (unsigned long,unsigned long,unsigned long)> const&,unsigned long&,unsigned long&,unsigned long&>(std::function<void (unsigned long,unsigned long,unsigned long)> const&,unsigned long&,unsigned long&,unsigned long&)::{lambda()#1}::  operator()  () const + 0x56
[0xb59b3c]          std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base,std::__future_base::_Result_base::_Deleter> (),std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>,std::__future_base::_Result_base::_Deleter>,std::_Bind_simple<std::reference_wrapper<std::future<std::result_of<std::function<void (unsigned long,unsigned long,unsigned long)> const& (unsigned long&,unsigned long&,unsigned long&)>::type> marian::ThreadPool::enqueue<std::function<void (unsigned long,unsigned long,unsigned long)> const&,unsigned long&,unsigned long&,unsigned long&>(std::function<void (unsigned long,unsigned long,unsigned long)> const&,unsigned long&,unsigned long&,unsigned long&)::{lambda()#1}> ()>,void>>::  _M_invoke  (std::_Any_data const&) + 0x2c
[0x66f689]          std::__future_base::_State_baseV2::  _M_do_set  (std::function<std::unique_ptr<std::__future_base::_Result_base,std::__future_base::_Result_base::_Deleter> ()>*,  bool*) + 0x29
[0x7fc7c20ffa99]                                                       + 0xea99
[0xb4b6f2]          std::_Function_handler<void (),std::future<std::result_of<std::function<void (unsigned long,unsigned long,unsigned long)> const& (unsigned long&,unsigned long&,unsigned long&)>::type> marian::ThreadPool::enqueue<std::function<void (unsigned long,unsigned long,unsigned long)> const&,unsigned long&,unsigned long&,unsigned long&>(std::function<void (unsigned long,unsigned long,unsigned long)> const&,unsigned long&,unsigned long&,unsigned long&)::{lambda()#3}>::  _M_invoke  (std::_Any_data const&) + 0xf2
[0x694cc4]          std::thread::_Impl<std::_Bind_simple<marian::ThreadPool::reserve(unsigned long)::{lambda()#1} ()>>::  _M_run  () + 0x174
[0x7fc7c1c1fc80]                                                       + 0xb8c80
[0x7fc7c20f86ba]                                                       + 0x76ba
[0x7fc7c138541d]    clone                                              + 0x6d

Aborted
```
I'm using pre-normalise and dropout as I am training in a (somewhat artificial) low resource setting and this gives me better BLEU scores, specifically on out-of-domain data. The issue appears with most combinations of:
```
transformer-postprocess: da
transformer-preprocess: n
```
Combined with any of the dropout settings:
```
transformer-dropout-attention: 0.1
transformer-dropout-ffn: 0.1
```
I'm reporting the issue because the model trains just fine on a 1080ti

**Comment by emjotde** [comment]
Not a good solution, but maybe a workaround for now. Run before training:
```export ENABLE_CUBLAS_TENSOR_OP_MATH_FP32=0```

That will be slower due to deactivated tensor cores, but probably avoids the NAN. The memory error is a separate bug.

**Comment by XapaJIaMnu** [comment]
Yes, `export ENABLE_CUBLAS_TENSOR_OP_MATH_FP32=0` seems to allow training to proceed as normal. Is this a marian bug then or a CUBLAS bug?

**Comment by kpu** [comment]
In FP16 it's easier to get out of range and generate infs that then cascade to NaNs.  It's not a bug in either, so much as a fact about floating-point formats that Marian could work around with more scaling factors.

**Comment by emjotde** [comment]
@XapaJIaMnu do you want to test the branch mjd/fp16.2 and add `--cost-scaling 1 200 0.05 10 1e-5` without the hack above? You can also test `--fp16` with that.

**Comment by XapaJIaMnu** [comment]
@emjotde this fixes the crash, and delays NAN, but not by that much:
```
[2020-09-05 20:21:44] [memory] Reserving 230 MB, device gpu4
[2020-09-05 20:22:04] Ep. 1 : Up. 100 : Sen. 46,750 : Cost 314.00448608 : Time 35.20s : 5532.88 words/s : gNorm 20126.2366
[2020-09-05 20:22:24] Ep. 1 : Up. 200 : Sen. 86,994 : Cost 211.39459229 : Time 20.37s : 3498.78 words/s : gNorm 35733.1837
[2020-09-05 20:22:42] Ep. 1 : Up. 300 : Sen. 137,255 : Cost nan : Time 17.18s : nan words/s : gNorm 41172.8250
[2020-09-05 20:22:59] Ep. 1 : Up. 400 : Sen. 184,785 : Cost nan : Time 17.13s : nan words/s : gNorm 40407.7559
```

**Comment by emjotde** [comment]
Maybe that GPU has throttled fp16 support or something?
Can you add `--log-level=debug` please?

**Comment by emjotde** [comment]
Another thing you may want to try is mini-batch warmup in addition to the learning rate warmup. We are seeing here that even the normalized gradient norms are crazy high (might be related to my question about final post-norm with pre-norm). So starting with a smaller mini-batch might avoid that until the model is out of crazy town. Try this after you give me the requested logs with `--log-level=debug`: `--mini-batch-warmup 1000` or larger values.

**Comment by XapaJIaMnu** [comment]
I tried a couple of configurations:
 - `-w 7000 --mini-batch-warmup 1000`
 - `-w 7000 --mini-batch-warmup 1000 --optimizer-delay 4`
 - `-w 7000 --mini-batch-warmup 10000`
 - `-w 7000 --mini-batch-warmup 100000`
 - `-w 7000 --mini-batch-warmup 1000 --fp16`
 - `-w 7000 --mini-batch-warmup 10000 --fp16`
 - `-w 3000 --mini-batch-warmup 10000`
You can find the logs and the basic config file [here](https://nbogoychev.com/files/marianlogs.tar.gz)
It seems your strategy works, for some of the configuration, but the model thinks too soon that it is out the woods:
```bash
grep "NaN/Inf percentage 0.00 after 200 gradient updates" *
warm100000.fp32:[2020-09-06 08:49:50] NaN/Inf percentage 0.00 after 200 gradient updates. Increasing cost-scaling factor to 0
warm10000.fp32:[2020-09-06 08:47:15] NaN/Inf percentage 0.00 after 200 gradient updates. Increasing cost-scaling factor to 0
warm1000.fp32:[2020-09-06 08:45:42] NaN/Inf percentage 0.00 after 200 gradient updates. Increasing cost-scaling factor to 0
warm1000.fp32.smallws:[2020-09-06 08:52:19] NaN/Inf percentage 0.00 after 200 gradient updates. Increasing cost-scaling factor to 0
```
I then tried changing cost scaling to: `--cost-scaling 0 10000 0 1 1e-5` and this seems to work, BUT training slows down to a crawl... I didn't wait for it to complete:
```
[2020-09-06 09:06:12] [memory] Allocating 242217984 bytes in device 5
[2020-09-06 09:06:12] [memory] Reserving 230 MB, device gpu4
[2020-09-06 09:06:12] [memory] Allocating 242217984 bytes in device 4
[2020-09-06 09:06:13] [data] fetched 428 batches with 91350 sentences. Per batch: 213.435 sentences, 3244.6 labels.
[2020-09-06 09:06:19] Ep. 1 : Up. 100 : Sen. 2,741 : Cost 296.81149292 : Time 22.15s : 17641.47 words/s : gNorm 1946.9701
[2020-09-06 09:06:27] Ep. 1 : Up. 200 : Sen. 9,821 : Cost 238.36575317 : Time 8.12s : 11153.44 words/s : gNorm 12825.0466
[2020-09-06 09:06:37] Ep. 1 : Up. 300 : Sen. 21,768 : Cost 189.29078674 : Time 9.55s : 6368.81 words/s : gNorm 19620.0856
[2020-09-06 09:06:48] Ep. 1 : Up. 400 : Sen. 38,325 : Cost 161.38371277 : Time 10.82s : 3877.71 words/s : gNorm 22948.3263
[2020-09-06 09:07:01] Ep. 1 : Up. 500 : Sen. 57,835 : Cost 130.93441772 : Time 13.19s : 2339.35 words/s : gNorm 28185.8128
[2020-09-06 09:07:16] Ep. 1 : Up. 600 : Sen. 84,121 : Cost 126.37892151 : Time 14.89s : 1969.06 words/s : gNorm 26434.9757
[2020-09-06 09:07:33] Ep. 1 : Up. 700 : Sen. 113,094 : Cost 108.67618561 : Time 17.08s : 1544.46 words/s : gNorm 28570.3153
[2020-09-06 09:07:51] Ep. 1 : Up. 800 : Sen. 149,642 : Cost 97.85311890 : Time 18.39s : 1307.61 words/s : gNorm 29502.3963
[2020-09-06 09:08:13] Ep. 1 : Up. 900 : Sen. 198,334 : Cost 86.24715424 : Time 21.97s : 975.58 words/s : gNorm 31681.5317
[2020-09-06 09:08:35] Ep. 1 : Up. 1000 : Sen. 244,429 : Cost 75.68672943 : Time 22.30s : 798.86 words/s : gNorm 33252.0871
[2020-09-06 09:08:58] Ep. 1 : Up. 1100 : Sen. 291,423 : Cost 66.11441803 : Time 22.59s : 600.27 words/s : gNorm 33225.3339
[2020-09-06 09:09:20] Ep. 1 : Up. 1200 : Sen. 338,776 : Cost 58.60851669 : Time 21.63s : 531.43 words/s : gNorm 31823.9029
[2020-09-06 09:09:42] Ep. 1 : Up. 1300 : Sen. 381,551 : Cost 47.65731430 : Time 22.84s : 367.78 words/s : gNorm 33416.4831
[2020-09-06 09:10:05] Ep. 1 : Up. 1400 : Sen. 435,595 : Cost 43.35261917 : Time 22.12s : 270.80 words/s : gNorm 32400.3262
[2020-09-06 09:10:27] Ep. 1 : Up. 1500 : Sen. 483,034 : Cost 34.58572388 : Time 22.57s : 174.35 words/s : gNorm 32446.4408
[2020-09-06 09:10:50] Ep. 1 : Up. 1600 : Sen. 531,943 : Cost 27.53565216 : Time 22.75s : 116.59 words/s : gNorm 32577.7189
[2020-09-06 09:11:12] Ep. 1 : Up. 1700 : Sen. 579,762 : Cost 22.45344162 : Time 22.18s : 77.55 words/s : gNorm 33242.3209
[2020-09-06 09:11:34] Ep. 1 : Up. 1800 : Sen. 631,711 : Cost 18.13187027 : Time 21.99s : 51.61 words/s : gNorm 31954.5209
[2020-09-06 09:11:56] Ep. 1 : Up. 1900 : Sen. 678,976 : Cost 13.37306404 : Time 22.34s : 27.77 words/s : gNorm 32062.9929
[2020-09-06 09:12:19] Ep. 1 : Up. 2000 : Sen. 725,671 : Cost 11.02127934 : Time 22.34s : 16.97 words/s : gNorm 31913.4654
```

I think the training speed is not very accurate though. Should I attempt to do a full run with this config?

Cheers,

Nick

**Comment by yuyang-huang** [comment]
Hi,

I've tried training a couple of pre-norm transformers with Marian lately. Not sure if it's related, but a possible issue I've noticed is that, in `LayerAttention`, the keys and values are not normalized. The `preProcess` function is applied to the `input` while `keys` and `values` are kept constant.

```c++
  Expr LayerAttention(std::string prefix,
                      Expr input,         // [-4: beam depth, -3: batch size, -2: max length, -1: vector dim]
                      const Expr& keys,   // [-4: beam depth=1, -3: batch size, -2: max length, -1: vector dim]
                      const Expr& values, // ...?
                      const Expr& mask,   // [-4: batch size, -3: num heads broadcast=1, -2: max length broadcast=1, -1: max length]
                      int dimHeads,
                      bool cache = false,
                      bool saveAttentionWeights = false) {
    int dimModel = input->shape()[-1];

    float dropProb = inference_ ? 0 : opt<float>("transformer-dropout");
    auto opsPre = opt<std::string>("transformer-preprocess");
    auto output = preProcess(prefix + "_Wo", opsPre, input, dropProb);

    // multi-head self-attention over previous input
    output = MultiHead(prefix, dimModel, dimHeads, output, keys, values, mask, cache, saveAttentionWeights);
    
    auto opsPost = opt<std::string>("transformer-postprocess");
    output = postProcess(prefix + "_Wo", opsPost, output, input, dropProb);

    return output;
  }
```

Also, in my case, adding an additional layer normalization after the final layer (of both the encoder and the decoder) is necessary. I've been doing something like:

```c++
    for(int i = 1; i <= encDepth; ++i) {
      // apply encoder layers
    }

    // additional layer normalization for pre-norm transformers
    if(opsPost.back() != 'n')
      layer = layerNorm(layer, prefix_ + "_top");
```

Without the above changes, I was also getting NaNs on 2080Ti while trying [Wang et al.](https://www.aclweb.org/anthology/P19-1176/) (base-sized 20-layer pre-norm transformers).

**Comment by emjotde** [comment]
@XapaJIaMnu Sorry, I messed up the command, should be `--cost-scaling 0 1000 2 0 1 1e-5`, the multiplication factor (2) was missing. Can you try again without the other stuff?

**Comment by emjotde** [comment]
@yuyang-huang Right, so we do need a final post-norm with pre-norm? I was suspecting this, when I asked if @XapaJIaMnu could veryify this. Is this confirmed anywhere in any of the reference implementations like Tensors2Tensor or Huggingface?

**Comment by yuyang-huang** [comment]
@emjotde I didn't check Tensor2Tensor, but it's in fairseq.

- Encoder: https://github.com/pytorch/fairseq/blob/0ffb94151f597ecb677551289e7046a21fb5ebaf/fairseq/models/transformer.py#L357-L360
- Decoder: https://github.com/pytorch/fairseq/blob/0ffb94151f597ecb677551289e7046a21fb5ebaf/fairseq/models/transformer.py#L596-L601

**Comment by emjotde** [comment]
@yuyang-huang Awesome, thank you. I was suspecting something was missing, but never got around to actually check. I will take a look at that code and your suggestion.

**Comment by XapaJIaMnu** [comment]
> @XapaJIaMnu Sorry, I messed up the command, should be `--cost-scaling 0 1000 2 0 1 1e-5`, the multiplication factor (2) was missing. Can you try again without the other stuff?

@emjotde , this seems to allow training to proceed on both float32 mode with tensorcores, as well as with float16. The only other thing I notice is that the speed reporting  (WPS) degrades with every mini-batch and is clearly not correct. I did not try training until convergence, just a few thousand mini-batches. Before, I used to see NaN after 200-300.

**Comment by emjotde** [comment]
That's really odd, the opposite should happen as the mini-batch size goes up?

**Comment by XapaJIaMnu** [comment]
@emjotde I assume you refer to the speed reporting. Notice that just the speed reporting itself is wrong, the training speed seems to be constant. Eg.:
```
[2020-09-07 20:19:42] Ep. 1 : Up. 1200 : Sen. 814,498 : Cost 46.49266052 : Time 17.27s : 258.47 words/s : gNorm 58620.6658
[2020-09-07 20:19:59] Ep. 1 : Up. 1300 : Sen. 880,269 : Cost 39.19552612 : Time 17.40s : 184.72 words/s : gNorm 60645.6733
[2020-09-07 20:20:16] Ep. 1 : Up. 1400 : Sen. 943,274 : Cost 31.84129906 : Time 16.81s : 149.16 words/s : gNorm 57896.5165
[2020-09-07 20:20:31] [data] fetched 0 batches with 0 sentences. Per batch: 0 sentences, 0 labels.
[2020-09-07 20:20:34] Ep. 1 : Up. 1500 : Sen. 1,009,453 : Cost 25.94668388 : Time 17.67s : 88.48 words/s : gNorm 60290.5750
[2020-09-07 20:20:49] Ep. 1 : Up. 1600 : Sen. 1,061,504 : Cost 20.59628868 : Time 15.43s : 66.12 words/s : gNorm 50291.1972
[2020-09-07 20:20:58] Seen 1,091,350 samples
[2020-09-07 20:20:58] Starting epoch 2
[2020-09-07 20:20:58] [data] Shuffling data
[2020-09-07 20:20:58] [data] Done shuffling 1,091,872 sentences (cached in RAM)
[2020-09-07 20:21:12] [data] fetched 1482 batches with 1000000 sentences. Per batch: 674.764 sentences, 10267.2 labels.
[2020-09-07 20:21:13] [data] fetched 175 batches with 91350 sentences. Per batch: 522 sentences, 7960.36 labels.
[2020-09-07 20:21:20] Ep. 2 : Up. 1700 : Sen. 31,688 : Cost 16.62148857 : Time 30.37s : 42.37 words/s : gNorm 30924.3120
[2020-09-07 20:21:37] Ep. 2 : Up. 1800 : Sen. 96,950 : Cost 12.38131714 : Time 17.34s : 26.07 words/s : gNorm 58638.8548
[2020-09-07 20:21:54] Ep. 2 : Up. 1900 : Sen. 155,995 : Cost 10.29944801 : Time 17.40s : 16.97 words/s : gNorm 58492.1513
[2020-09-07 20:22:11] Ep. 2 : Up. 2000 : Sen. 228,803 : Cost 9.39095020 : Time 16.61s : 15.11 words/s : gNorm 59028.2935
```
Notice how it's more or less ~17 seconds per mini-batch, more or less similar amount of sentences but the training speed is reported lower and lower.

**Comment by emjotde** [comment]
Nah, something is off. That would require some more investigation. Maybe we can do that live via Messenger at some point.

**Comment by emjotde** [comment]
OK, #719 seems to fix the huge gradient norm issue. So it should also protect against the NaNs from the beginning. The other solutions proposed here by me are mostly hacks to get around that.

**Comment by emjotde** [comment]
Closing this with PR #719
