### ISSUE TITLE
NCCL error 2 'unhandled system error' only with 4 GPUs

### ISSUE THREAD

**Issue by laklaja** [marian-nmt/marian-dev#899]
### Bug description
I would like to train a transformer-big marian model. I could start training, with 1 and 2 GPUs, but if I tried it with 4 GPUs I reached the following error message (full log file attached). 
```
...
[2022-01-13 14:49:59] [batching] Collecting statistics for batch fitting with step size 10
[2022-01-13 14:49:59] [MPI rank 0 out of 1]: GPU[0]
[2022-01-13 14:49:59] [MPI rank 0 out of 1]: GPU[1]
[2022-01-13 14:49:59] [MPI rank 0 out of 1]: GPU[2]
[2022-01-13 14:49:59] [MPI rank 0 out of 1]: GPU[3]
[2022-01-13 14:49:59] [memory] Extending reserved space to 9088 MB (device gpu0)
[2022-01-13 14:50:00] [memory] Extending reserved space to 9088 MB (device gpu1)
[2022-01-13 14:50:00] [memory] Extending reserved space to 9088 MB (device gpu2)
[2022-01-13 14:50:00] [memory] Extending reserved space to 9088 MB (device gpu3)
[2022-01-13 14:50:00] [comm] Using NCCL 2.8.3 for GPU communication
[2022-01-13 14:50:00] [comm] Using global sharding
[2022-01-13 14:50:23] Error: NCCL error 2 'unhandled system error' - /marian/src/training/communicator_nccl.h:43: ncclGroupEnd()
[2022-01-13 14:50:23] Error: Aborted from void marian::NCCLCommunicator::groupEnd() const in /marian/src/training/communicator_nccl.h:43

[CALL STACK]
[0x55a209e1ff6a]    marian::NCCLCommunicator::  groupEnd  () const     + 0x21a
[0x55a209e34e88]    marian::NCCLCommunicator::  NCCLCommunicator  (std::vector<std::shared_ptr<marian::ExpressionGraph>,std::allocator<std::shared_ptr<marian::ExpressionGraph>>> const&,  marian::ShardingMode,  std::shared_ptr<marian::IMPIWrapper>) + 0x2da8
[0x55a209e3863a]    std::shared_ptr<marian::NCCLCommunicator> marian::  New  <marian::NCCLCommunicator,std::vector<std::shared_ptr<marian::ExpressionGraph>,std::allocator<std::shared_ptr<marian::ExpressionGraph>>> const&,marian::ShardingMode&,std::shared_ptr<marian::IMPIWrapper>&>(std::vector<std::shared_ptr<marian::ExpressionGraph>,std::allocator<std::shared_ptr<marian::ExpressionGraph>>> const&,  marian::ShardingMode&,  std::shared_ptr<marian::IMPIWrapper>&) + 0x6a
[0x55a209e11044]    marian::  createCommunicator  (std::vector<std::shared_ptr<marian::ExpressionGraph>,std::allocator<std::shared_ptr<marian::ExpressionGraph>>> const&,  bool,  marian::ShardingMode,  std::shared_ptr<marian::IMPIWrapper>) + 0x3a4
[0x55a209da7daf]    marian::GraphGroup::  GraphGroup  (std::shared_ptr<marian::Options>,  std::shared_ptr<marian::IMPIWrapper>) + 0x59f
[0x55a209d8bacd]    marian::SyncGraphGroup::  SyncGraphGroup  (std::shared_ptr<marian::Options>,  std::shared_ptr<marian::IMPIWrapper>) + 0x7d
[0x55a209837044]    std::shared_ptr<marian::SyncGraphGroup> marian::  New  <marian::SyncGraphGroup,std::shared_ptr<marian::Options>&,std::shared_ptr<marian::IMPIWrapper>&>(std::shared_ptr<marian::Options>&,  std::shared_ptr<marian::IMPIWrapper>&) + 0x84
[0x55a2098b5b11]    marian::Train<marian::SyncGraphGroup>::  run  ()   + 0x311
[0x55a2097bf312]    mainTrainer  (int,  char**)                        + 0xe2
[0x55a2097757dc]    main                                               + 0x3c
[0x7f4a5b3a20b3]    __libc_start_main                                  + 0xf3
[0x55a2097bdfae]    _start                                             + 0x2e
...
```
I have just upgraded my host machine to Ubuntu 20.04, but I execute marian under docker. 
```
$ nvidia-docker version
NVIDIA Docker: 2.8.0
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Nvidia-smi:
```
Thu Jan 13 14:51:04 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.86       Driver Version: 470.86       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:02:00.0 Off |                  N/A |
| 20%   37C    P0    60W / 250W |      1MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:03:00.0 Off |                  N/A |
| 29%   38C    P0    60W / 250W |      1MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:81:00.0 Off |                  N/A |
| 20%   46C    P0    60W / 250W |      1MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:82:00.0 Off |                  N/A |
| 27%   34C    P0    61W / 250W |      1MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

### Context
* Marian version: v1.10.26; c84599d0 2021-12-16 15:07:55 +0000
* CMake command: cmake .. -DUSE_SENTENCEPIECE=on -DCOMPILE_CPU=on -DUSE_MPI=ON -DUSE_NCCL=ON -DUSE_CUDNN=ON
[marian_build_info.txt](https://github.com/marian-nmt/marian-dev/files/7863461/marian_build_info.txt)
* Log file: [train_marian.log](https://github.com/marian-nmt/marian-dev/files/7863338/train_marian.log)
* Docker file: [Dockerfile.txt](https://github.com/marian-nmt/marian-dev/files/7863491/Dockerfile.txt)

Thanks your kind help.

**Comment by XapaJIaMnu** [comment]
I just noticed this, sorry. Most likely your issue is  you are compiling with MPI support  but you are trying to run on a single node, which is not well tested. Just compile with the default flags `cmake ..`, everything else should be left as default unless you know what you are doing.

**Comment by laklaja** [comment]
Thanks for your answer. I have tried out several different parameter settings, but I haven't found the solution yet.  I will try it out.   I am not familiar with MPI, so I would like to ask, is MPI a library for multi-node computation? I would like to use my multi-GPU server (one node) correctly to reach the best training time. I know there are several issues here, and I haven't done my deep research on them.

**Comment by XapaJIaMnu** [comment]
MPI is a library that implements parallelism through message parsing. You can read more about it on the internet https://en.wikipedia.org/wiki/Message_Passing_Interface

On a single machine it is usually faster to use multiple GPUs through inter-thread communication without MPI and this is the default (and the fastest except in some corner cases) for a single machine, multiple GPUs.

**Comment by laklaja** [comment]
Thanks a lot. I removed MPI from my installation and I haven't reached this issue again.

**Comment by AmitMY** [comment]
Hi, I am actually getting the same error - despite it saying (first line) "Compiled without MPI support".
Is there anything else that needs changing?

> [2022-08-18 18:30:50] [comm] Compiled without MPI support. Running as a single process on 21b3ef8c3f7f
> [2022-08-18 18:30:50] Synced seed 1660847450
> [2022-08-18 18:30:50] [data] Loading SentencePiece vocabulary from file /training/models/spoken-signed/spoken_to_signed/vocab/vocab.spm
> [2022-08-18 18:30:50] [data] Setting vocabulary size for input 0 to 32,000
> [2022-08-18 18:30:50] [data] Loading SentencePiece vocabulary from file /training/models/spoken-signed/spoken_to_signed/vocab/vocab.spm
> [2022-08-18 18:30:50] [data] Setting vocabulary size for input 1 to 32,000
> [2022-08-18 18:30:50] [batching] Collecting statistics for batch fitting with step size 10
> [2022-08-18 18:30:54] [memory] Extending reserved space to 4096 MB (device gpu0)
> [2022-08-18 18:30:55] [memory] Extending reserved space to 4096 MB (device gpu1)
> [2022-08-18 18:30:55] [memory] Extending reserved space to 4096 MB (device gpu2)
> [2022-08-18 18:30:55] [memory] Extending reserved space to 4096 MB (device gpu3)
> [2022-08-18 18:30:56] [comm] Using NCCL 2.8.3 for GPU communication
> [2022-08-18 18:30:56] [comm] Using global sharding
> [2022-08-18 18:31:18] Error: NCCL error 2 'unhandled system error' - /firefox-translations-training/3rd_party/marian-dev/src/training/communicator_nccl.h:43: ncclGroupEnd()
> [2022-08-18 18:31:18] Error: Aborted from void marian::NCCLCommunicator::groupEnd() const in /firefox-translations-training/3rd_party/marian-dev/src/training/communicator_nccl.h:43
>

**Comment by benjamin-marie** [comment]
I had the same error. Disabling NCCL before compilation worked for me (MPI was already deactivated by default).
I use CUDA 11.8 and 1 RTX 3060 GPU (so no need of NCCL in my case).

**Comment by AmitMY** [comment]
My full error:
```log
[2023-11-11 10:24:05] [memory] Extending reserved space to 4096 MB (device gpu0)
[2023-11-11 10:24:05] [memory] Extending reserved space to 4096 MB (device gpu1)
[2023-11-11 10:24:05] [memory] Extending reserved space to 4096 MB (device gpu2)
[2023-11-11 10:24:06] [memory] Extending reserved space to 4096 MB (device gpu3)
[2023-11-11 10:24:06] [comm] Using NCCL 2.8.3 for GPU communication
[2023-11-11 10:24:06] [comm] Using global sharding
[2023-11-11 10:24:27] Error: NCCL error 2 'unhandled system error' - /firefox-translations-training/3rd_party/marian-dev/src/training/communicator_nccl.h:43: ncclGroupEnd()
[2023-11-11 10:24:27] Error: Aborted from void marian::NCCLCommunicator::groupEnd() const in /firefox-translations-training/3rd_party/marian-dev/src/training/communicator_nccl.h:43

[CALL STACK]
[0x5653ac54a2cb]    marian::NCCLCommunicator::  groupEnd  () const     + 0x21b
[0x5653ac553988]    marian::NCCLCommunicator::  NCCLCommunicator  (std::vector<std::shared_ptr<marian::ExpressionGraph>,std::allocator<std::shared_ptr<marian::ExpressionGraph>>> const&,  marian::ShardingMode,  std::shared_ptr<marian::IMPIWrapper>) + 0x2bc8
[0x5653ac529c40]    marian::  createCommunicator  (std::vector<std::shared_ptr<marian::ExpressionGraph>,std::allocator<std::shared_ptr<marian::ExpressionGraph>>> const&,  bool,  marian::ShardingMode,  std::shared_ptr<marian::IMPIWrapper>) + 0x300
[0x5653ac4d22e8]    marian::GraphGroup::  GraphGroup  (std::shared_ptr<marian::Options>,  std::shared_ptr<marian::IMPIWrapper>) + 0x598
[0x5653ac4bfe43]    marian::SyncGraphGroup::  SyncGraphGroup  (std::shared_ptr<marian::Options>,  std::shared_ptr<marian::IMPIWrapper>) + 0x73
[0x5653abfe9650]    std::shared_ptr<marian::SyncGraphGroup> marian::  New  <marian::SyncGraphGroup,std::shared_ptr<marian::Options>&,std::shared_ptr<marian::IMPIWrapper>&>(std::shared_ptr<marian::Options>&,  std::shared_ptr<marian::IMPIWrapper>&) + 0x70
[0x5653ac063460]    marian::Train<marian::SyncGraphGroup>::  run  ()   + 0x280
[0x5653abf85d28]    mainTrainer  (int,  char**)                        + 0xc8
[0x5653abf4104a]    main                                               + 0x8a
[0x7f8c4f00ac87]    __libc_start_main                                  + 0xe7
[0x5653abf8360a]    _start                                             + 0x2a
```


After setting `NCCL_DEBUG=TRACE`


```log
[2023-11-11 10:27:44] [memory] Extending reserved space to 4096 MB (device gpu0)
[2023-11-11 10:27:44] [memory] Extending reserved space to 4096 MB (device gpu1)
[2023-11-11 10:27:44] [memory] Extending reserved space to 4096 MB (device gpu2)
[2023-11-11 10:27:45] [memory] Extending reserved space to 4096 MB (device gpu3)
[2023-11-11 10:27:45] [comm] Using NCCL 2.8.3 for GPU communication
[2023-11-11 10:27:45] [comm] Using global sharding
70573403c8a4:30882:30882 [3] NCCL INFO Bootstrap : Using eth0:172.17.0.2<0>
70573403c8a4:30882:30882 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
70573403c8a4:30882:30882 [3] NCCL INFO NET/IB : No device found.
70573403c8a4:30882:30882 [3] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0>
70573403c8a4:30882:30882 [3] NCCL INFO Using network Socket
NCCL version 2.8.3+cuda11.5
70573403c8a4:30882:30897 [0] NCCL INFO Channel 00/02 :    0   1   2   3
70573403c8a4:30882:30897 [0] NCCL INFO Channel 01/02 :    0   1   2   3
70573403c8a4:30882:30898 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0
70573403c8a4:30882:30899 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1
70573403c8a4:30882:30900 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2
70573403c8a4:30882:30897 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
70573403c8a4:30882:30898 [1] NCCL INFO Setting affinity for GPU 1 to 0f,ff000fff
70573403c8a4:30882:30899 [2] NCCL INFO Setting affinity for GPU 2 to 0f,ff000fff
70573403c8a4:30882:30900 [3] NCCL INFO Setting affinity for GPU 3 to 0f,ff000fff
70573403c8a4:30882:30897 [0] NCCL INFO Setting affinity for GPU 0 to 0f,ff000fff
70573403c8a4:30882:30898 [1] NCCL INFO Could not enable P2P between dev 1(=1b000) and dev 0(=1a000)
70573403c8a4:30882:30900 [3] NCCL INFO Could not enable P2P between dev 3(=3e000) and dev 2(=3d000)
70573403c8a4:30882:30897 [0] NCCL INFO Could not enable P2P between dev 0(=1a000) and dev 3(=3e000)
70573403c8a4:30882:30899 [2] NCCL INFO Could not enable P2P between dev 2(=3d000) and dev 1(=1b000)

70573403c8a4:30882:30899 [2] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
70573403c8a4:30882:30899 [2] NCCL INFO include/shm.h:41 -> 2

70573403c8a4:30882:30899 [2] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-bdb4fb571cdada60-0-1-2 (size 9637888)

70573403c8a4:30882:30899 [2] NCCL INFO transport/shm.cc:101 -> 2
70573403c8a4:30882:30899 [2] NCCL INFO transport.cc:30 -> 2
70573403c8a4:30882:30899 [2] NCCL INFO transport.cc:76 -> 2
70573403c8a4:30882:30899 [2] NCCL INFO init.cc:813 -> 2
70573403c8a4:30882:30899 [2] NCCL INFO init.cc:878 -> 2

70573403c8a4:30882:30897 [0] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
70573403c8a4:30882:30897 [0] NCCL INFO include/shm.h:41 -> 2

70573403c8a4:30882:30897 [0] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-bdb4fb571cdada60-0-3-0 (size 9637888)

70573403c8a4:30882:30897 [0] NCCL INFO transport/shm.cc:101 -> 2
70573403c8a4:30882:30897 [0] NCCL INFO transport.cc:30 -> 2
70573403c8a4:30882:30897 [0] NCCL INFO transport.cc:76 -> 2
70573403c8a4:30882:30897 [0] NCCL INFO init.cc:813 -> 2
70573403c8a4:30882:30899 [2] NCCL INFO group.cc:72 -> 2 [Async thread]
70573403c8a4:30882:30897 [0] NCCL INFO init.cc:878 -> 2
70573403c8a4:30882:30897 [0] NCCL INFO group.cc:72 -> 2 [Async thread]

70573403c8a4:30882:30900 [3] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
70573403c8a4:30882:30900 [3] NCCL INFO include/shm.h:41 -> 2

70573403c8a4:30882:30900 [3] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-bdb4fb571cdada60-0-2-3 (size 9637888)

70573403c8a4:30882:30900 [3] NCCL INFO transport/shm.cc:101 -> 2
70573403c8a4:30882:30900 [3] NCCL INFO transport.cc:30 -> 2
70573403c8a4:30882:30900 [3] NCCL INFO transport.cc:76 -> 2
70573403c8a4:30882:30900 [3] NCCL INFO init.cc:813 -> 2
70573403c8a4:30882:30900 [3] NCCL INFO init.cc:878 -> 2
70573403c8a4:30882:30900 [3] NCCL INFO group.cc:72 -> 2 [Async thread]

70573403c8a4:30882:30898 [1] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
70573403c8a4:30882:30898 [1] NCCL INFO include/shm.h:41 -> 2

70573403c8a4:30882:30898 [1] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-bdb4fb571cdada60-0-0-1 (size 9637888)

70573403c8a4:30882:30898 [1] NCCL INFO transport/shm.cc:101 -> 2
70573403c8a4:30882:30898 [1] NCCL INFO transport.cc:30 -> 2
70573403c8a4:30882:30898 [1] NCCL INFO transport.cc:76 -> 2
70573403c8a4:30882:30898 [1] NCCL INFO init.cc:813 -> 2
70573403c8a4:30882:30898 [1] NCCL INFO init.cc:878 -> 2
70573403c8a4:30882:30898 [1] NCCL INFO group.cc:72 -> 2 [Async thread]
[2023-11-11 10:27:45] Error: NCCL error 2 'unhandled system error' - /firefox-translations-training/3rd_party/marian-dev/src/training/communicator_nccl.h:43: ncclGroupEnd()
[2023-11-11 10:27:45] Error: Aborted from void marian::NCCLCommunicator::groupEnd() const in /firefox-translations-training/3rd_party/marian-dev/src/training/communicator_nccl.h:43

[CALL STACK]
[0x5651f594a2cb]    marian::NCCLCommunicator::  groupEnd  () const     + 0x21b
[0x5651f5953988]    marian::NCCLCommunicator::  NCCLCommunicator  (std::vector<std::shared_ptr<marian::ExpressionGraph>,std::allocator<std::shared_ptr<marian::ExpressionGraph>>> const&,  marian::ShardingMode,  std::shared_ptr<marian::IMPIWrapper>) + 0x2bc8
[0x5651f5929c40]    marian::  createCommunicator  (std::vector<std::shared_ptr<marian::ExpressionGraph>,std::allocator<std::shared_ptr<marian::ExpressionGraph>>> const&,  bool,  marian::ShardingMode,  std::shared_ptr<marian::IMPIWrapper>) + 0x300
[0x5651f58d22e8]    marian::GraphGroup::  GraphGroup  (std::shared_ptr<marian::Options>,  std::shared_ptr<marian::IMPIWrapper>) + 0x598
[0x5651f58bfe43]    marian::SyncGraphGroup::  SyncGraphGroup  (std::shared_ptr<marian::Options>,  std::shared_ptr<marian::IMPIWrapper>) + 0x73
[0x5651f53e9650]    std::shared_ptr<marian::SyncGraphGroup> marian::  New  <marian::SyncGraphGroup,std::shared_ptr<marian::Options>&,std::shared_ptr<marian::IMPIWrapper>&>(std::shared_ptr<marian::Options>&,  std::shared_ptr<marian::IMPIWrapper>&) + 0x70
[0x5651f5463460]    marian::Train<marian::SyncGraphGroup>::  run  ()   + 0x280
[0x5651f5385d28]    mainTrainer  (int,  char**)                        + 0xc8
[0x5651f534104a]    main                                               + 0x8a
[0x7fbc87dd4c87]    __libc_start_main                                  + 0xe7
[0x5651f538360a]    _start                                             + 0x2a
```

Which does not make sense, since `nvidia-smi` shows the gpus are empty
<img width="628" alt="image" src="https://github.com/marian-nmt/marian-dev/assets/5757359/14b5acd7-18cf-4f6a-bb7b-aa0c5a8583fd">

So I look at the NCCL Version, and in the log it says `Using NCCL 2.8.3 for GPU communication`, but `apt list libnccl2 libnccl-dev` says I have `2.11.4-1+cuda11.5` installed in `/usr/lib/x86_64-linux-gnu/libnccl.so` (and I know it is the correct version for my machine, since it's just installed with the docker image `nvidia/cuda:11.5.2-devel-ubuntu18.04`)

`marian-dev` seems to find NCCL based on https://github.com/marian-nmt/marian-dev/blob/master/cmake/FindNCCL.cmake
I have `/usr/include/nccl.h` with `NCCL_VERSION_CODE 21104` and `/firefox-translations-training/3rd_party/marian-dev/build/local/include/nccl.h` with `NCCL_VERSION_CODE 2803`, so clearly it is using the one in the build, and I can't find where it is installing it. 

Last hail marry attempt - recompiled `marian-dev` with `-DUSE_STATIC_LIBS=on`, but I still have `marian-dev/build/local/include/nccl.h` with `2803`. 

How can I tell `marian-dev` to use my installed version?

**Comment by AmitMY** [comment]
With some external help, I find that `export NCCL_SHM_DISABLE=1` makes the process run on all 4 GPUs, increasing my throughput from `26,318.99 words/s` to `44,707.07 words/s`.
